<a href="https://colab.research.google.com/github/johanjun/Google_Machine_Learning_Bootcamp_KR_2021/blob/main/codes/(Coursera)_Python_and_Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Coursera DL Specialization Week1 Python Demo

## 1. Vectorization
-  whenever possible avoid explicit for-loops!


In [3]:
import numpy as np
import time

In [2]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [4]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print("Ventorized version : ", str(1000*(toc-tic)) + "ms")

Ventorized version :  1.4507770538330078ms


In [5]:
c = 0
tic = time.time()

for i in range(1000000):
  c += a[i]*b[i]

toc = time.time()

print("for loop : " + str(1000*(toc-tic)) + "ms")

for loop : 644.6554660797119ms


## 2. Broadcasting

In [6]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [7]:
cal = A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [8]:
percentage = 100*A/cal
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


## 3. Python-Numpy vectors

In [9]:
a = np.random.randn(5)
print(a)

[ 0.91927973 -0.36374133  2.71451691  0.05051994 -0.47084405]


In [10]:
print(a.shape) # rank1 (Don't use)

(5,)


In [12]:
print(a.T)

[ 0.91927973 -0.36374133  2.71451691  0.05051994 -0.47084405]


In [13]:
print(np.dot(a, a.T))

8.570231435026642


In [14]:
a = np.random.randn(5, 1)
print(a)

[[-0.18705036]
 [ 2.04790994]
 [-0.86282333]
 [-0.29017948]
 [-0.74633708]]


In [16]:
print(a.shape)

(5, 1)


In [15]:
print(a.T)

[[-0.18705036  2.04790994 -0.86282333 -0.29017948 -0.74633708]]


In [17]:
print(np.dot(a, a.T))

[[ 0.03498784 -0.3830623   0.16139142  0.05427818  0.13960262]
 [-0.3830623   4.19393513 -1.76698448 -0.59426145 -1.52843113]
 [ 0.16139142 -1.76698448  0.7444641   0.25037363  0.64395705]
 [ 0.05427818 -0.59426145  0.25037363  0.08420413  0.21657171]
 [ 0.13960262 -1.52843113  0.64395705  0.21657171  0.55701904]]
